package com.fpt.parser.logtype.view
import com.fpt.parser.common.InfoRequestUriColumn

class InfoRequestUriColumnView extends InfoRequestUriColumn {
  val  fieldScn = FieldInRequestUriColumn("scn", """[\?+&+]scn=[^&]*""", "string")
  val  fieldUid = FieldInRequestUriColumn("uid", """[\?+&+]uid=[^&]*""", "string")
  val  fieldDml = FieldInRequestUriColumn("dml", """[\?+&+]dml=[^&]*""", "string")
  val  fieldOst = FieldInRequestUriColumn("ost", """[\?+&+]ost=[^&]*""", "string")
  val  fieldScc = FieldInRequestUriColumn("scc", """[\?+&+]scc=[^&]*""", "string")
  val  fieldInm = FieldInRequestUriColumn("inm", """[\?+&+]inm=[^&]*""", "string")
  val  fieldAv = FieldInRequestUriColumn("av", """[\?+&+]av=[^&]*""", "string")
  val  fieldTrackingview = FieldInRequestUriColumn("trackingView", """[\?+&+]trackingView=[^&]*""", "string")
  val  fieldEv = FieldInRequestUriColumn("ev", """[\?+&+]ev=[^&]*""", "string")
  val  fieldScp = FieldInRequestUriColumn("scp", """[\?+&+]scp=[^&]*""", "string")
  val  fieldUtm_campaign = FieldInRequestUriColumn("utm_campaign", """[\?+&+]utm_campaign=[^&]*""", "string")
  val  fieldScv = FieldInRequestUriColumn("scv", """[\?+&+]scv=[^&]*""", "string")
  val  fieldTz = FieldInRequestUriColumn("tz", """[\?+&+]tz=[^&]*""", "string")
  val  fieldFmv = FieldInRequestUriColumn("fmv", """[\?+&+]fmv=[^&]*""", "string")
  val  fieldRes = FieldInRequestUriColumn("res", """[\?+&+]res=[^&]*""", "string")
  val  fieldOv = FieldInRequestUriColumn("ov", """[\?+&+]ov=[^&]*""", "string")
  val  fieldUtm_medium = FieldInRequestUriColumn("utm_medium", """[\?+&+]utm_medium=[^&]*""", "string")
  val  fieldScid = FieldInRequestUriColumn("scid", """[\?+&+]scid=[^&]*""", "string")
  val  fieldTv = FieldInRequestUriColumn("tv", """[\?+&+]tv=[^&]*""", "string")
  val  fieldT6 = FieldInRequestUriColumn("t6", """[\?+&+]t6=[^&]*""", "string")
  val  fieldNt = FieldInRequestUriColumn("nt", """[\?+&+]nt=[^&]*""", "string")
  val  fieldEla = FieldInRequestUriColumn("ela", """[\?+&+]ela=[^&]*""", "string")
  val  fieldEca = FieldInRequestUriColumn("eca", """[\?+&+]eca=[^&]*""", "string")
  val  fieldAst = FieldInRequestUriColumn("ast", """[\?+&+]ast=[^&]*""", "string")
  val  fieldEac = FieldInRequestUriColumn("eac", """[\?+&+]eac=[^&]*""", "string")
  val  fieldUtm_source = FieldInRequestUriColumn("utm_source", """[\?+&+]utm_source=[^&]*""", "string")
  val  fieldIid = FieldInRequestUriColumn("iid", """[\?+&+]iid=[^&]*""", "string")
  val  fieldMac = FieldInRequestUriColumn("mac", """[\?+&+]mac=[^&]*""", "string")
  val  fieldDvt = FieldInRequestUriColumn("dvt", """[\?+&+]dvt=[^&]*""", "string")
  val  fieldLvid = FieldInRequestUriColumn("lvid", """[\?+&+]lvid=[^&]*""", "string")
  val  fieldLvt = FieldInRequestUriColumn("lvt", """[\?+&+]lvt=[^&]*""", "string")
  val  fieldDmf = FieldInRequestUriColumn("dmf", """[\?+&+]dmf=[^&]*""", "string")
  val  fieldDtm = FieldInRequestUriColumn("dtm", """[\?+&+]dtm=[^&]*""", "string")
  val  fieldDid = FieldInRequestUriColumn("did", """[\?+&+]did=[^&]*""", "string")
  val  fieldT4 = FieldInRequestUriColumn("t4", """[\?+&+]t4=[^&]*""", "string")
  val  fieldT5 = FieldInRequestUriColumn("t5", """[\?+&+]t5=[^&]*""", "string")
  val  fieldT2 = FieldInRequestUriColumn("t2", """[\?+&+]t2=[^&]*""", "string")
  val  fieldT3 = FieldInRequestUriColumn("t3", """[\?+&+]t3=[^&]*""", "string")
  val  fieldT1 = FieldInRequestUriColumn("t1", """[\?+&+]t1=[^&]*""", "string")
  val  fieldEpn = FieldInRequestUriColumn("epn", """[\?+&+]epn=[^&]*""", "string")
  val  fieldP = FieldInRequestUriColumn("p", """[\?+&+]p=[^&]*""", "string")
  val  fieldAisp = FieldInRequestUriColumn("aisp", """[\?+&+]aisp=[^&]*""", "string")
  val  fieldTna = FieldInRequestUriColumn("tna", """[\?+&+]tna=[^&]*""", "string")
  val  fieldEid = FieldInRequestUriColumn("eid", """[\?+&+]eid=[^&]*""", "string")
  val  fieldTos = FieldInRequestUriColumn("tos", """[\?+&+]tos=[^&]*""", "string")
  val  fieldAid = FieldInRequestUriColumn("aid", """[\?+&+]aid=[^&]*""", "string")
  val  fieldCtn = FieldInRequestUriColumn("ctn", """[\?+&+]ctn=[^&]*""", "string")
  val  fieldLvn = FieldInRequestUriColumn("lvn", """[\?+&+]lvn=[^&]*""", "string")

}
